// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/health": {
            "get": {
                "description": "Проверка, что процесс жив (без обращения к БД)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.HealthResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/ready": {
            "get": {
                "description": "Проверка готовности сервиса, включая Postgres",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ReadyResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error — текст ошибки.",
                    "type": "string",
                    "example": "database unavailable"
                }
            }
        },
        "model.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "Status — статус сервиса (ok).",
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "model.ReadyResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "Status — статус готовности (ready).",
                    "type": "string",
                    "example": "ready"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "chistotel.webtm.ru",
	BasePath:         "/babasub",
	Schemes:          []string{"https"},
	Title:            "VPN Subscription Service API",
	Description:      "Сервис выдачи VPN-подписок (v1 scaffold: health/ready).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
